# -*- coding: utf-8 -*-
"""Imersão Python - Alura.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14IEmmr5RsVpelqz5MffJLJTI_dJnw5vo

**Aula 2 - Importação**
"""

import pandas as pd
import plotly.express as px

df_principal = pd.read_excel('/content/Imersão Python - Tabela de ações.xlsx', sheet_name='Principal')
df_principal

df_chatgpt = pd.read_excel('/content/Imersão Python - Tabela de ações.xlsx', sheet_name='chat_gpt')
df_chatgpt

df_total_de_acoes = pd.read_excel('/content/Imersão Python - Tabela de ações.xlsx', sheet_name='Total_de_acoes')
df_total_de_acoes

df_ticker = pd.read_excel('/content/Imersão Python - Tabela de ações.xlsx', sheet_name='Ticker')
df_ticker

df_principal = df_principal[['Ativo', 'Data', 'Último (R$)', 'Var. Dia (%)']].copy()
df_principal

df_principal = df_principal.rename(columns={'Ativo':'ativo', 'Data':'data', 'Último (R$)':'ultimo_valor_real', 'Var. Dia (%)':'variacao_dia'}).copy()
df_principal

df_principal['variacao_dia_porcentagem'] = df_principal['variacao_dia'] / 100
df_principal

df_principal['valor_real_inicial_dia'] = df_principal['ultimo_valor_real'] / (df_principal['variacao_dia_porcentagem'] + 1)
df_principal

df_principal = df_principal.merge(df_total_de_acoes, left_on='ativo', right_on='Código', how='left')
df_principal

df_principal = df_principal.drop(columns=['Código'])
df_principal

df_principal = df_principal.rename(columns={'Qtde. Teórica': 'quantidade_teorica'}).copy()
df_principal

df_principal['variacao_total_dia'] = (df_principal['ultimo_valor_real'] - df_principal['valor_real_inicial_dia']) * df_principal['quantidade_teorica']
df_principal

pd.options.display.float_format = '{:.2f}'.format
df_principal

df_principal['resultado'] = df_principal['variacao_total_dia'].apply(lambda x: 'Subiu' if x > 0 else ('Desceu' if x < 0 else 'estavel'))
df_principal

df_principal = df_principal.merge(df_ticker, left_on='ativo', right_on='Ticker', how='left')
df_principal

df_principal = df_principal.rename(columns={'Ticker':'ticker', 'Nome':'nome'})
df_principal

df_principal = df_principal.drop(columns=['ticker'])
df_principal

df_principal = df_principal.merge(df_chatgpt, left_on='nome', right_on='Empresa', how='left')
df_principal

df_principal = df_principal.drop(columns={'Empresa'})
df_principal

df_principal = df_principal.rename(columns={'Segmento':'segmento', 'Idade (em anos)':'idade'})
df_principal

df_principal['nova_coluna'] = df_principal['idade'].apply(lambda x: "Maior que 100" if x > 100 else "Maior que 50" if x > 50 else "Menor que 50" if x < 50 else "Igual a 50" if x == 50 else "")
df_principal

# Calcular o maior valor
maior_valor = df_principal['variacao_total_dia'].max()

# Calcular o menor valor
menor_valor = df_principal['variacao_total_dia'].min()

# Calcular a média geral
media_geral = df_principal['variacao_total_dia'].mean()

# Calcular a média de quem subiu
media_subiu = df_principal[df_principal['resultado'] == 'Subiu']['variacao_total_dia'].mean()

# Calcular a média de quem desceu
media_desceu = df_principal[df_principal['resultado'] == 'Desceu']['variacao_total_dia'].mean()

# Exibir os resultados
print("Maior valor:", maior_valor)
print("Menor valor:", menor_valor)
print("Média geral:", media_geral)
print("Média de quem subiu:", media_subiu)
print("Média de quem desceu:", media_desceu)

df_media_subiu = df_principal[df_principal['resultado'] == 'Subiu']
df_media_subiu

df_analise_segmento = df_media_subiu.groupby('segmento')['variacao_total_dia'].sum().reset_index()
df_analise_segmento

df_analise_saldo = df_principal.groupby('resultado')['variacao_total_dia'].sum().reset_index()
df_analise_saldo

fig = px.bar(df_analise_saldo, x='resultado', y='variacao_total_dia', text='variacao_total_dia', title='Variação Reais por Resultados')
fig.show()